@startuml
class Emoticon {
    + Emoticon()
    + AddShape(shape:Shape) : void
    + AddMemento(shape:Shape) : void
    + RemoveShape(type:Type) : void
    + Undo() : void
    + Redo() : void
    + Contains(type:Type) : bool
    + Move(shape:Shape, direction:int, value:int) : void
    + Rotate(shape:Shape, direction:int, degrees:int) : void
    + Display() : void
    + drawSVG() : List<string>
    + ToSVG() : void
}
class "List`1"<T> {
}
Emoticon --> "emoticon<Shape>" "List`1"
Emoticon o-> "history<Memento>" "List`1"
Emoticon o-> "redoList<Memento>" "List`1"
@enduml
